import pytest
from lpie.stages.registry import StageRegistry
from lpie.stages.ingest import IngestStage
from lpie.stages.contract import ContractStage
from lpie.stages.label import LabelStage
from lpie.stages.split import SplitStage
from lpie.stages.features import FeaturesStage
from lpie.stages.train import TrainStage
from lpie.stages.anomaly import AnomalyStage
from lpie.stages.explain import ExplainStage
from lpie.stages.narrate import NarrateStage
from lpie.stages.submit import SubmitStage


def test_no_llm_artifacts_in_submission_transitive_inputs():
    """
    Principle I static graph enforcement:
    Verify that no artifact generated by the LLM stage (narrate) is present in the
    transitive input closure of the submit stage.
    """
    registry = StageRegistry()
    registry.register(IngestStage())
    registry.register(ContractStage())
    registry.register(LabelStage())
    registry.register(SplitStage())
    registry.register(FeaturesStage())
    registry.register(TrainStage())
    registry.register(AnomalyStage())
    registry.register(ExplainStage())
    registry.register(NarrateStage())
    registry.register(SubmitStage())

    transitive_inputs = registry.get_transitive_input_artifacts("submit")
    narrate_outputs = set(NarrateStage().declared_outputs)

    overlap = transitive_inputs.intersection(narrate_outputs)
    assert len(overlap) == 0, f"Principle I VIOLATION: Submission pipeline depends on LLM artifacts: {overlap}"
